name: Update requirements.txt

on:
  push:
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  generate-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipreqs
        run: pip install pipreqs

      - name: Generate requirements.txt
        run: pipreqs . --force

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add requirements.txt
          git commit -m "chore: auto-update requirements.txt" || echo "No changes to commit"
          git push
